<script type="text/javascript">
	window.onload=function(){
	var mtiTracking=document.createElement('link');
	mtiTracking.type='text/css';
	mtiTracking.rel='stylesheet';
	mtiTracking.href=('https:'==document.location.protocol?'https:':'http:')+'//fast.fonts.com/t/1.css?apiType=css&projectid=56de8e1b-86b5-4643-aded-995484241284';
	(document.getElementsByTagName('head')[0]||document.getElementsByTagName('body')[0]).appendChild( mtiTracking );
	}
</script>